Repository jeremmfr/terraform-provider-junos, pull requests merged in 2025-02, with the labels that each got.

#748 Security dynamic address with fwk
  .changes/security-dynamic-address-with-fwk.md
  docs/resources/security_dynamic_address_feed_server.md
  docs/resources/security_dynamic_address_name.md
  internal/providerfwk/provider.go
  internal/providerfwk/resource_security_dynamic_address_feed_server.go
  internal/providerfwk/resource_security_dynamic_address_feed_server_test.go
  internal/providerfwk/resource_security_dynamic_address_name.go
  internal/providerfwk/resource_security_dynamic_address_name_test.go
  internal/providerfwk/testdata/TestAccResourceSecurityDynamicAddressFeedServer_basic/1/main.tf
  internal/providerfwk/testdata/TestAccResourceSecurityDynamicAddressFeedServer_basic/2/main.tf
  internal/providerfwk/testdata/TestAccResourceSecurityDynamicAddressName_basic/1/main.tf
  internal/providerfwk/testdata/TestAccResourceSecurityDynamicAddressName_basic/4/main.tf
  internal/providerfwk/testdata/TestAccUpgradeStateResourceSecurityDynamicAddressName_V0toV1_basic/1/main.tf
  internal/providerfwk/testdata/TestAccUpgradeStateResourceSecurityDynamicAddressName_V0toV1_basic/1/provider.tf
  internal/providerfwk/testdata/TestAccUpgradeStateResourceSecurityDynamicAddressName_V0toV1_basic/2/main.tf
  internal/providerfwk/upgradestate_security_security_dynamic_address_name.go
  internal/providerfwk/upgradestate_security_security_dynamic_address_name_test.go
  internal/providersdk/provider.go
  internal/providersdk/resource_security_dynamic_address_feed_server.go
  internal/providersdk/resource_security_dynamic_address_feed_server_test.go
  internal/providersdk/resource_security_dynamic_address_name.go
  internal/providersdk/resource_security_dynamic_address_name_test.go
Labels: enhancement, refactor, plugin-framework

#749 r/forwardingoptions_dhcprelay_servergroup: ip_address argument is no longer ordered
  .changes/forwardingoptions-dhcprelay-servergroup-ip-address-order.md
  docs/resources/forwardingoptions_dhcprelay_servergroup.md
  internal/providerfwk/resource_forwardingoptions_dhcprelay_servergroup.go
Labels: enhancement

#750 feat: add virtual gateway for ipv4
  docs/resources/interface_logical.md
  internal/providerfwk/resource_interface_logical.go
Labels: enhancement

#751 add virtual gateway to logical interface
  .changes/logical-interface-virtual-gateway.md
  docs/data-sources/interface_logical.md
  docs/resources/interface_logical.md
  internal/providerfwk/data_source_interface_logical.go
  internal/providerfwk/data_source_interface_logical_test.go
  internal/providerfwk/resource_access_address_assignment_pool.go
  internal/providerfwk/resource_interface_logical.go
  internal/providerfwk/testdata/TestAccDataSourceInterfaceLogical_basic/1/main.tf
  internal/providerfwk/testdata/TestAccDataSourceInterfaceLogical_basic/2/main.tf
  internal/providerfwk/testdata/TestAccResourceInterfaceLogical_router/1/main.tf
  internal/providerfwk/testdata/TestAccResourceInterfaceLogical_router/2/main.tf
Labels: enhancement

#755 tests: bump golangci-lint to v1.64.5
  .github/workflows/linters.yml
  .golangci.yml
Labels: tests

#756 r/security: add routing_instance argument in idp_security_package block
  .changes/issue-754.md
  docs/resources/security.md
  internal/providerfwk/resource_security.go
  internal/providerfwk/testdata/TestAccResourceSecurity_basic/4/main.tf
Labels: enhancement

#757 r/igmp_snooping_vlan: use new provider via framework
  .changes/igmp-snooping-vlan-with-fwk.md
  internal/providerfwk/provider.go
  internal/providerfwk/resource_igmp_snooping_vlan.go
  internal/providerfwk/resource_igmp_snooping_vlan_test.go
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_basic/1/main.tf
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_basic/1/variables.tf
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_basic/2/main.tf
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_basic/2/variables.tf
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_switch/1/main.tf
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_switch/1/variables.tf
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_switch/2/main.tf
  internal/providerfwk/testdata/TestAccResourceIgmpSnoopingVlan_switch/2/variables.tf
  internal/providersdk/constants.go
  internal/providersdk/func_common.go
  internal/providersdk/func_resource_routing_instance.go
  internal/providersdk/provider.go
  internal/providersdk/resource_igmp_snooping_vlan.go
  internal/providersdk/resource_igmp_snooping_vlan_test.go
Labels: enhancement, refactor, plugin-framework

#760 r/routing_options: use new provider via framework
  .changes/routing-options-with-fwk.md
  docs/resources/routing_options.md
  internal/providerfwk/provider.go
  internal/providerfwk/resource_routing_options.go
  internal/providerfwk/resource_routing_options_test.go
  internal/providerfwk/testdata/TestAccResourceRoutingOptions_basic/1/main.tf
  internal/providerfwk/testdata/TestAccResourceRoutingOptions_basic/3/main.tf
  internal/providerfwk/testdata/TestAccUpgradeStateResourceRoutingOptions_V0toV1_basic/1/main.tf
  internal/providerfwk/testdata/TestAccUpgradeStateResourceRoutingOptions_V0toV1_basic/1/provider.tf
  internal/providerfwk/testdata/TestAccUpgradeStateResourceRoutingOptions_V0toV1_basic/2/main.tf
  internal/providerfwk/upgradestate_routing_options.go
  internal/providerfwk/upgradestate_routing_options_test.go
  internal/providersdk/provider.go
  internal/providersdk/resource_routing_options.go
  internal/providersdk/resource_routing_options_test.go
Labels: enhancement, refactor, plugin-framework
